export default [
	// {
	// 	text: 'Ingresar',
	// 	path: '/ingresar-articulo',
	// 	name: 'ingresar',
	// 	component: '@/views/Ingresar',
	// 	can: 'article.store',
	// },
	{
		text: 'Reportes',
		path: '/reportes',
		component: '@/views/Reportes',
		image_url: 'nav-icons/caja.png',
		name: 'reportes',
		can: 'reportes',
		params: {
			view: 'generales',
		},
	},
	{
		text: 'Listado',
		path: '/listado-de-articulos',
		model_name: 'article',
		component: '@/views/Listado',
		can: 'article.index',
		image_url: 'nav-icons/listado.png',
	},
	{
		text: 'Vender',
		path: '/vender',
		name: 'vender',
		component: '@/views/Vender',
		can: 'sale.store',
		params: {
			view: 'remito',
		},
		if_has_extencion: 'comerciocity_interno',
		image_url: 'nav-icons/vender.png',
	},
	{
		path: '/deposito-para-checkear',
		text: 'Deposito',
		name: 'deposito-para-checkear',
		component: '@/views/DepositoParaCheckear',
		can: 'deposito_para_checkear',
		image_url: 'nav-icons/ventas-to-check.png',
		if_has_extencion: 'check_sales',
		params: {
			view: 'para-checkear',
		},
	},
	{
		path: '/deposito-checkeadas',
		text: 'Checkeadas',
		name: 'deposito-checkeadas',
		component: '@/views/DepositoCheckeadas',
		can: 'deposito_checkeadas',
		image_url: 'nav-icons/ventas-checked.png',
		if_has_extencion: 'check_sales',
	},
	{
		path: '/ventas',
		model_name: 'sale',
		component: '@/views/Ventas',
		can: 'sale.index',
		params: {
			view: 'todas',
			sub_view: 'todos',
		},
		image_url: 'nav-icons/ventas.png',
	},
	{
		text: 'Ventas',
		path: '/ventas-completas',
		name: 'VentasAll',
		model_name: 'sale',
		component: '@/views/Ventas',
		can: 'sale.index',
		params: {
			view: 'todas',
			sub_view: 'todos',
		},
		not_show: true,
	},
	{
		path: '/proveedores',
		model_name: 'provider',
		component: '@/views/Provider',
		can: 'provider.index',
		params: {
			view: 'proveedores',
		},
		if_has_extencion: 'comerciocity_interno',
		image_url: 'nav-icons/proveedores.png',
	},
	{
		path: '/clientes',
		model_name: 'client',
		component: '@/views/Client',
		can: 'client.index',
		params: {
			view: 'clientes',
		},
		if_has_extencion: 'comerciocity_interno',
		image_url: 'nav-icons/clientes.png',
	},
	{
		text: 'Panel de Control',
		path: '/panel-de-control',
		component: '@/views/PanelDeControl',
		image_url: 'nav-icons/caja.png',
		name: 'panel',
		params: {
			view: 'proveedores',
			sub_view: 'rendimiento-general',
		},
	},
	{
		path: '/presupuestos',
		model_name: 'budget',
		component: '@/views/Budget',
		can: 'budget.index',
		if_has_extencion: ['budgets', 'comerciocity_interno'],
		image_url: 'nav-icons/presupuestos.png',
	},
	{
		text: 'Online',
		name: 'online',
		path: '/online',
		component: '@/views/Online',
		params: {
			view: 'pedidos',
		},
		if_has_extencion: 'online',
		can: [
			'order.index',
			'buyer.index',
		],
		image_url: 'nav-icons/tienda.png',
	},
	{
		text: 'MercadoLibre',
		name: 'mercado_libre',
		path: '/mercado-libre',
		component: '@/views/MercadoLibre',
		params: {
			view: 'pedidos',
		},
		if_has_extencion: 'mercado_libre',
		can: [
			'mercado_libre.orders',
		],
		image_url: 'nav-icons/mercado_libre.png',
	},
	{
		text: 'Produccion',
		path: '/produccion',
		name: 'produccion',
		component: '@/views/Produccion',
		can: 'produccion.index',
		function: 'toProduccion',
		if_has_extencion: ['production', 'comerciocity_interno'],
		can: [
			'production_movement.index',
			'order_production.index',
			'recipe.index',
		],
		image_url: 'nav-icons/produccion.png',
	},
	{
		text: 'Caja',
		path: '/caja',
		name: 'caja',
		model_name: 'report',
		component: '@/views/Caja',
		params: {
			view: 'reportes',
		},
		if_has_extencion: 'comerciocity_interno',
		image_url: 'nav-icons/caja.png',
		can: 'caja.reports',
	},
	{
		text: 'ABM',
		name: 'abm',
		params: {
			view: 'listado',
			sub_view: 'categorias',
			model_name: 'category',
		},
		can: 'abm',
		image_url: 'nav-icons/abm.png',
	},
	{
		model_name: 'employee',
		name: 'employee',
		path: '/empleados',
		component: '@/common-vue/views/Employee',
		check_is_owner: true,
		if_has_extencion: 'comerciocity_interno',
		image_url: 'nav-icons/empleados.png',
	},
]