export default [
    // 'extencion',
    'unidad_frecuencia',
    'afip_selected_payment_method',
    'current_acount_payment_method_discount',
    'afip_information',
    'expense_concept',
    'current_acount_payment_method',
    'article_pre_import_range',
    'price_type',
    'order_production_status',
    'unidad_medida',
    'article',
    'article_property_type',
    'article_property_value',
    'task',
    'provider',
    'client',
    'employee',
    'permission',
    'address',
    'sale_type',
    'discount',
    'surchage',
    'brand',
    'category',
    'condition',
    'recipe',
    'iva',
    'iva_condition',
    'sub_category',
    'location',
    'seller',
    'provider_order_status',
    'order_status',
    'payment_method',
    'payment_method_type',
    // 'commission',
    'commission',
    'delivery_zone',
    'budget_status',
    'sale',
    // 'credit_card',
    // 'credit_card_payment_plan',
    'order',
    'online_price_type',
    // 'buyer',
    'inventory_linkage_scope',
    'article_ticket_info',
]