export default {
	properties: [
		{
			text: 'N°',
			key: 'num',
			type: 'text',
			value: '',
			show: true,
			not_show_on_form: true,
			use_to_filter_in_search: true,
			filter_modal_position: 8,
		},
		{
			text: 'Nombre',
			key: 'name',
			type: 'text',
			value: '',
			show: true,
			use_to_filter_in_search: true,
			use_to_filter_in_modal: true,
			filter_modal_position: 1,
		},
		{
			text: 'Saldo',
			key: 'saldo',
			only_show: true,
			type: 'number',
			value: '',
			show: true,
			is_price: true,
			use_to_filter_in_modal: true,
			filter_modal_position: 2,
		},
		{
			text: 'Telefono',
			key: 'phone',
			type: 'text',
			value: '',
			show: true,
			use_to_filter_in_modal: true,
		},
		{
			text: 'Correo',
			key: 'email',
			type: 'text',
			value: '',
			not_show: true,
		},
		{
			text: 'Direccion',
			key: 'address',
			type: 'text',
			value: '',
			not_show: true,
			use_to_filter_in_modal: true,
		},
		{
			text: 'Tipo de precio',
			key: 'price_type_id',
			type: 'select',
			value: 0,
			show: true,
			use_store_models: true,
			use_to_filter_in_modal: true,
			filter_modal_position: 6,
		},
		{
			text: 'Localidad',
			key: 'location_id',
			type: 'search',
			use_store_models: true,
			use_to_filter_in_modal: true,
			filter_modal_position: 4,
		},
		{
			text: 'Cuit',
			key: 'cuit',
			type: 'text',
			value: '',
			show: true,
			use_to_filter_in_search: true,
			filter_modal_position: 5,
		},
		{
			text: 'Cuil',
			key: 'cuil',
			type: 'text',
			value: '',
			show: true,
			use_to_filter_in_search: true,
		},
		{
			text: 'Razon social',
			key: 'razon_social',
			type: 'text',
			not_show: true,
			value: '',
		},
		{
			text: 'Condicion frente al IVA',
			key: 'iva_condition_id',
			type: 'select',
			value: 0,
			not_show: true,
			use_store_models: true,
			use_to_filter_in_modal: true,
			filter_modal_position: 7,
		},
		{
			text: 'Descripcion',
			key: 'description',
			type: 'textarea',
			value: '',
			show: true,
		},
		{
			text: 'Vendedor',
			key: 'seller_id',
			type: 'select',
			value: 0,
			not_show: true,
			use_store_models: true,
			filter_modal_position: 3,
		},
	],
	plural_model_name_spanish: 'Clientes',
	singular_model_name_spanish: 'Cliente',
	create_model_name_spanish: 'Nuevo cliente',
	text_delete: 'el',
	show_all_models_on_display: false,
}